name: Welcome New Contributors

on:
  pull_request_target:
    types: [opened]
    branches: [main]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  welcome:
    runs-on: ubuntu-latest
    
    steps:
      - name: Welcome New Contributor
        run: |
          echo "🎉 Welcome to CanConf, @${{ github.event.pull_request.user.login }}!"
          echo ""
          echo "PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          echo "Author: ${{ github.event.pull_request.user.login }}"
          echo "Profile: ${{ github.event.pull_request.user.html_url }}"
          echo ""
          echo "Your contribution helps make Canadian tech events more discoverable for everyone! 🇨🇦"
          echo ""
          echo "Once this PR is merged, you'll be automatically added to our contributors list on the website."
          echo ""
          echo "Thank you for contributing to the Canadian tech community!"

      - name: Post welcome comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = "${{ github.event.pull_request.user.login }}";
            const prNumber = ${{ github.event.pull_request.number }};
            
            const message = `🎉 Thank you for contributing to CanConf, @${username}! 
            
            Your contribution helps make Canadian tech events more discoverable for everyone. 🇨🇦
            
            Once this PR is merged, you'll be automatically added to our contributors list on the website!
            
            ---
            *This comment was automatically generated by our contributor recognition system.*`;
            
            try {
              const result = await github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
              console.log('✅ Welcome comment posted successfully!');
              console.log('Comment URL:', result.data.html_url);
            } catch (error) {
              console.error('❌ Failed to post comment:', error.message);
              console.log('ℹ️ This might be due to insufficient permissions or the PR being from a fork.');
              console.log('The welcome message above is still visible in the workflow logs.');
            }
